default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "todo_ajax_datatable_development" } %>

test:
  <<: *default
  database: todo_ajax_datatable_test

production:
  <<: *default
  database: ajax-jquery-crud_production
  username: ajax-jquery-crud
  password: <%= ENV['AJAX-JQUERY-CRUD_DATABASE_PASSWORD'] %>
